//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStudentRegisterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentLastName { get; set; }
        public string StudentMail { get; set; }
        public string StudentPhoto { get; set; }
        public string StudentAdress { get; set; }
    }
}
